random_seed: 42
codec: "encodec"
dataset: "expresso"
device: "cuda"
gpus: "0"

ckpt_path: "/project2/shrikann_35/nmehlman/logs/private_codecs/test_ckpt.cptk"
num_samples_to_save: 10

# Dataset options:
dataset:
  dataset_path: "/project2/shrikann_35/DATA/expresso/codec_feats/encodec" 

# Dataloader options:
dataloader:
  batch_size: 32
  num_workers: 4

save_path: "/project2/shrikann_35/nmehlman/logs/private_codecs/eval/uninformed_expresso_encodec"