random_seed: 42
codec: "encodec"
dataset: "expresso"
device: "cuda"
gpus: "0"

ckpt_path: "/project2/shrikann_35/nmehlman/logs/private_codecs/test_ckpt.cptk"
num_samples_to_save: 10

lightning:
  codec_dim: 128
  latent_dim: 128
  enc_channels: [128, 64, 32]
  dec_channels: [32, 64, 128]
  conditioning_dim: 256
  num_emotion_classes: 9
  adv_loss_weight: 1.0
  learning_rate: 0.001
  weight_decay: 0
  adv_annealing_steps: 500
  adv_update_factor: 1

emotion_conditioning_model: "wavlm"

# Dataset options:
data_args:
  data_dir: "/project2/shrikann_35/DATA/expresso/" 

# Dataloader options:
dataloader:
  batch_size: 32
  num_workers: 4

save_path: "/project2/shrikann_35/nmehlman/logs/private_codecs/eval/uninformed_expresso_encodec"