random_seed: 42
gpus: "1"
ckpt_path: null

dataset:
  dataset: "msp_podcast"
  codec: "encodec"
  data_type: "quantized_embedding"
  val_frac: 0.1

dataloader:
  batch_size: 32
  num_workers: 4

model:
  input_dim: 128
  num_classes: 9
  lr: 0.0005

# Training options:
trainer:
  max_epochs: 100
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: True

# Tensorboard options:
tensorboard:
  save_dir: "/data1/nmehlman/logs/priv-codec/embed_predictor/msp/encodec"
  name: "test_run"
  version: null 