

# Basic training configuration for Expresso with Encodec features

---
random_seed: 42
ckpt_path: null
gpus: "0"
dataset_name: "expresso"
codec_name: "hificodec"
input_type: "quantized_embedding"

# Dataset options:
dataset:
  dataset_path: "/project2/shrikann_35/DATA/expresso/codec_feats/"
  codec: "hificodec"
  emotion_model: "wavlm"

# Dataloader options:
dataloader:
  batch_size: 64
  num_workers: 4

# Model options:
lightning:
  codec_dim: 128
  latent_dim: 64
  enc_channels: [256]
  dec_channels: [128]
  conditioning_dim: 256
  conditioning_dropout: 0.4
  num_emotion_classes: 9
  adversarial_channels: [64, 64, 64]
  adv_loss_weight: 0.02
  learning_rate: 0.001
  weight_decay: 0
  adv_annealing_steps: 1000
  adv_update_factor: 2
  normalize_input: true


# Training options:
trainer:
  max_epochs: 150
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: True

# Tensorboard options:
tensorboard:
  save_dir: "/project2/shrikann_35/nmehlman/logs/private_codecs/tensorboard"
  name: "dropout"
  version: null     # Automatic versioning if set to null (recommended)

