task: "categorical_emotion"
codec: "bigcodec"
dataset: "msp_podcast"

data_args:
  data_dir: "/data1/open_data/MSP-Podcast-1.11/"
  split: "development"

device: "cuda:0"
batch_size: 16

save_path: "/data1/nmehlman/logs/priv-codec/benchmarking/emotion/bigcodec-msp_podcast.pkl"