task: "categorical_emotion"
codec_name: "hificodec"
dataset_name: "expresso"

dataset:
  data_dir: "/project2/shrikann_35/DATA/expresso/"
  split: "train"

device: "cuda"

save_path: "/project2/shrikann_35/DATA/expresso/codec_feats/hificodec/train"
