task: "categorical_emotion"
codec: "encodec"
dataset: "expresso"

data_args:
  data_dir: "/project2/shrikann_35/DATA/expresso/"
  split: "train"

device: "cuda"

save_path: "/project2/shrikann_35/DATA/expresso/codec_feats/encodec/train"