task: "categorical_emotion"
codec_name: "encodec"
dataset_name: "expresso"

data_args:
  data_dir: "/project2/shrikann_35/DATA/expresso/"
  split: "test"

device: "cuda"

save_path: "/project2/shrikann_35/DATA/expresso/codec_feats/encodec/test"
