task: "categorical_emotion"
codec_name: "bigcodec"
dataset_name: "expresso"

data_args:
  data_dir: "/project2/shrikann_35/DATA/expresso/"
  split: "train"

device: "cuda"

save_path: "/project2/shrikann_35/DATA/expresso/codec_feats/bigcodec/train"
