random_seed: 42
dataset_name: "expresso"
codec_name: "encodec"
input_type: "quantized_embedding"
device: "cuda"
gpus: "0"

log_dir: "/project2/shrikann_35/nmehlman/logs/private_codecs/tensorboard/smaller_bottleneck/version_0"
ckpt_name: "epoch=84-step=95370.ckpt"
num_samples_to_save: 10
strategy: "random" # "exhaustive", "targeted", "random"
target_emotion: "Neutral"  # Used only if strategy is "targeted"

lightning:
  codec_dim: 128
  latent_dim: 32
  enc_channels: [256]
  dec_channels: [256]
  conditioning_dim: 256
  num_emotion_classes: 9
  adv_loss_weight: 0.0
  learning_rate: 0.001
  weight_decay: 0
  adv_annealing_steps: 500
  adv_update_factor: 1
  adversarial_channels: [64, 64, 64]

emotion_conditioning_model: "wavlm"

# Dataset options:
dataset:
  data_dir: "/project2/shrikann_35/DATA/expresso/" 
