task: "categorical_emotion"
codec: "hificodec"
dataset: "msp_podcast"

data_args:
  data_dir: "/data1/open_data/MSP-Podcast-1.11/"
  split: "train"

device: "cuda:2"

save_path: "/data/nmehlman/priv-codecs-data/emotion_embeddings/msp_podcast/hificodec/train"