task: "categorical_emotion"
codec: "bigcodec"
dataset: "expresso"

data_args:
  data_dir: "/data1/open_data/expresso/"
  split: "train"

device: "cuda:1"

save_path: "/data/nmehlman/priv-codecs-data/emotion_embeddings/expresso/bigcodec/train"